### ISSUE TITLE
Mapbox custom markers

### ISSUE THREAD

**Issue by AndrewHaine** [AndrewHaine/statamic-cartographer#1]
Not as tricky as initially thought, should be possible following this: https://docs.mapbox.com/help/tutorials/custom-markers-gl-js/

**Comment by jsblair9** [comment]
So I ended up doing a quick implementation like this just to get things started. I think the style way is ok too... but this way would let you upload the marker from the cp and have better access to it without having to create a new style (which may be easier for most)

```js
// /resources/assets/js/cartographer_mapbox.js:32

data.markers.forEach(marker => {
    var el = document.createElement('div');
    el.className = 'marker';

    var markerObject = new mapboxgl.Marker({
        element: el,
        anchor: 'bottom',
        offset: [0, 7]
        // color: marker.color
    });
    markerObject.setLngLat([marker.position.lng, marker.position.lat]).addTo(map);
});
```
And then added a `.marker` class that contains the custom marker svg
```css
.marker {
  background-image: url('../../svg/icon-marker.svg');
  background-size: cover;
  width: 40px;
  height: 70px;
  cursor: pointer;
}
```
